### ISSUE TITLE
healthcheck endpoint without auth

### ISSUE THREAD

**Issue by eMCeee89** [ipfs-cluster/ipfs-cluster#1884]
I am trying to run IPFS cluster in AWS, I followed an AWS documentation https://aws.amazon.com/blogs/containers/deploying-ipfs-cluster-using-aws-fargate-and-amazon-efs-one-zone/

What I found interesting is that a load-balancer's target group checks ipfs-cluster on endpoint `/id` and expects return code 401 because basic auth is enabled.

I tried to configure LB target group to evaluate `/monitor/metrics/ping` endpoint instead but that is also expecting auth which is not possible to configure for AWS load-balancer target group healthchecks.

It would be great if you can expose such a simple endpoint that will reply with 200 when everything is OK even without authentication to make the service cloud-ready.

Thank you.

**Comment by hsanjuan** [comment]
Yeah, that's fair...

Must it be http checks or can tcp checks also be used? As a workaround, perhaps you can enable a different API without authentication (i.e. the pinsvc one or the metrics endpoints) and use it to health check without exposing it to the world. I'm not sure if that works given it listen on a different port etc.

In any case, having a /health endpoint that bypasses auth is worth doing for the next release if we have time.

**Comment by eMCeee89** [comment]
Thank You for taking care of this one. Neither TCP health-checks nor health-checking a different port as configured for targets within the target group is possible. It is currently livable to get 401s but is is quite ugly solution that also produces a lot of ERRORs in ipfs-cluster container logs.

**Comment by arthurgavazza** [comment]
I'm gonna pick this up if that's ok. Do you know if someone started working on it ? @hsanjuan

**Comment by hsanjuan** [comment]
> I'm gonna pick this up if that's ok. Do you know if someone started working on it ? @hsanjuan

Thanks, go ahead.

**Comment by arthurgavazza** [comment]
@hsanjuan I have a few questions
1. Should I just create a rest endpoint that returns 200, or the /health route should have any other logic in it?
2. I found the authHandler here https://github.com/ipfs-cluster/ipfs-cluster/blob/master/api/common/api.go and the rest api is created using  the _common.NewAPIWithHost_  function which adds the authHandler to all api routes, how can I disable auth for a specific route? 

sorry for the  questions, I'm  not very familiar with ipfs-cluster yet.

**Comment by hsanjuan** [comment]
Regarding the Auth handler, there is a [passthrough for OPTIONS requests](https://github.com/ipfs-cluster/ipfs-cluster/blob/master/api/common/api.go#L305-L308), you should add a passthrough for GET requests to `/health` right next to it.

Regarding the /health endpoint, take the `/token` endpoint as example. Create a HealthHandler function in the `api` package so that it can be re-used by all APIs. Then add :

```
		{
			Name:        "Health",
			Method:      "GET",
			Pattern:     "/health",
			HandlerFunc: api.HealthHandler,
		},
```

to the routes slice in both restapi and pinsvc apis.

For the time being, let it just return 204 - No content. We can iterate or add some logic later.

Also, you will need to add:

* Tests (see TESTAPIVersionEndpoint) for example in restapi_test.go.
* Client support in restapi/client (i.e. a Health(ctx) method in client/methods.go, plus updating the Client interface).

Most of it is replicating how things are done for other simple endpoints, like the /version one.

**Comment by arthurgavazza** [comment]
@hsanjuan thank you for the guidance! I'll open a PR tomorrow morning
